2024-06-09 10:47:46,233 ERROR: Exception on /auth/login [GET] [in /home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/alucard/python/kfu/minkin2024/app/auth/routes.py", line 16, in login
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/werkzeug/local.py", line 515, in _get_current_object
    return get_name(local())
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask_login/utils.py", line 25, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask_login/utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask_login/login_manager.py", line 347, in _load_user
    raise Exception(
Exception: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info.
2024-06-09 10:48:50,284 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:75]
2024-06-09 10:48:54,589 ERROR: Exception on /auth/login [GET] [in /home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/alucard/python/kfu/minkin2024/app/auth/routes.py", line 16, in login
    if current_user.is_authenticated:
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/werkzeug/local.py", line 515, in _get_current_object
    return get_name(local())
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask_login/utils.py", line 25, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask_login/utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask_login/login_manager.py", line 347, in _load_user
    raise Exception(
Exception: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info.
2024-06-09 10:50:13,591 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:75]
2024-06-09 10:50:15,395 ERROR: Exception on /auth/login [GET] [in /home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/alucard/python/kfu/minkin2024/app/auth/routes.py", line 28, in login
    return render_template('auth/login.html', title='Sign In', form=form)
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/templating.py", line 151, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: auth/login.html
2024-06-09 11:26:39,042 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:78]
2024-06-09 11:27:40,878 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:78]
2024-06-09 11:27:52,863 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:78]
2024-06-09 11:28:08,247 ERROR: Exception on /user/alucard [GET] [in /home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/alucard/python/kfu/minkin2024/app/main/routes.py", line 24, in user
    1 / 0
ZeroDivisionError: division by zero
2024-06-09 11:29:33,519 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:78]
2024-06-09 11:29:39,074 ERROR: Exception on /user/alucard [GET] [in /home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/alucard/python/kfu/minkin2024/app/main/routes.py", line 24, in user
    1 / 0
ZeroDivisionError: division by zero
2024-06-09 11:32:10,137 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:78]
2024-06-09 11:32:43,961 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:78]
